#! /usr/bin/env dcli

import 'dart:io';
import 'package:dcli/dcli.dart';

/// dcli script generated by:
/// dcli create bleed.dart
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///

void main(List<String> args) {
  'apt update -y'.start(privileged: true);
  'apt upgrade -y --allow-downgrades'.start(privileged: true);
  'apt autoremove -y'.start(privileged: true);
  green('Bleading complete. Keep boolin, King');
}
