name: bleed
version: 1.0.1
description: auto update tool for apt package managers.
environment: 
  sdk: '>=2.9.0 <3.0.0'
dependencies: 
  args: ^1.0.0
  dcli: ^0.32.0
  path: ^1.0.0
dev_dependencies: 
  pedantic: ^1.0.0
executables:
  bleed:
